name: Déploiement GitHub Pages & Firebase Hosting

on:
  push:
    branches:
      - main

# Permissions requises pour GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Évite les déploiements concurrents simultanés
concurrency:
  group: 'deploy-all'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment-pages.outputs.page_url }}

    steps:
      # 1. Récupération du code
      - name: Checkout du code
        uses: actions/checkout@v4

      # 2. Configuration de Node.js et Build
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Installation et Build
        run: |
          npm ci --legacy-peer-deps
          npm run build

      # ---------------------------------------------
      # DÉPLOIEMENT GITHUB PAGES
      # ---------------------------------------------
      - name: Configuration GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload de l'artefact pour GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Déploiement sur GitHub Pages
        id: deployment-pages
        uses: actions/deploy-pages@v4

      # ---------------------------------------------
      # DÉPLOIEMENT FIREBASE HOSTING
      # ---------------------------------------------
      - name: Déploiement sur Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CASHPOWERMETTERPRO }}'
          channelId: live
          projectId: cashpowermetterpro
